### PR TITLE
Dec 2018 update

### PR DESCRIPTION
**Pull request by paulopsgility**

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Hi Paul, 
Please verify that this update addresses open issues #11 & #12 
Thanks,
Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Feedback received via email from Sanjay Soni:
One feedback was about getting SQL Server 2017 instead of SQL Server 2016 in the pictures/diagrams..Please let us know. thanks

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility @Jeff-Opsgility 
Hello,
We have received sign-off to complete this update.  Please make any final changes, close any open issues and send to your editors. Let me know when it's ready for me to QC/merge.
Thanks, Dawnmarie

****Note from tech lead**:  There is a planned presentation of this workshop on Feb. 6th.  Please complete as soon as possible.  Thanks!

**Comment by paulopsgility** [comment]
@DawnmarieDesJardins this is ready for QC/merge

**Pull request merged**
